version: '3'
services:
  app:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/rabbit_test
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass password
    volumes:
      - 'redis:/data'
  db:
    image: postgres:10.4-alpine
    stdin_open: true
    tty: true
    ports:
      - "6379:6379"
volumes:
  redis: