default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:

development:
  <<: *default
  database: rabbit_test_development

test:
  <<: *default
  database: rabbit_test

production:
  <<: *default
  database: rabbit_test_production
  username: rabbit_test
  password: <%= ENV['RABBIT_TEST_DATABASE_PASSWORD'] %>
